In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

# Vectorizacion -> Python, NumPy

In [3]:
# vectores con numpy 
a = np.zeros(4)
print(f"a = {a} > type : {a.dtype}")
a = np.zeros((4,))
print(f"a = {a} > type : {a.dtype}")
a = np.random.random_sample(4)
print(f"a = {a} > type : {a.dtype}")

a = [0. 0. 0. 0.] > type : float64
a = [0. 0. 0. 0.] > type : float64
a = [0.41599466 0.37972315 0.02625675 0.31501054] > type : float64


In [4]:
#operacion con vectores
a = np.arange(10)
print(a)

#acceder al elemento 
try:
    c = a[9]
except Exception as err:
    print("error")

[0 1 2 3 4 5 6 7 8 9]


In [5]:
print(c)

9


In [6]:
#Slicing 
#slicin crea un array usando tres valores (inicio:fin:pasos) 

a = np.arange(10)
print(a)

c = a[2:-1]
print(c)

d = a[3:-1]
print(d)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[3 4 5 6 7 8]


In [7]:
#Operaciones con vectores 
a = np.array([1,2,3,4])

sum_vector = a.sum()
print(f"suma del vector : {sum_vector}")

mean_vector = a.mean()
print(f"promedio del vector : {mean_vector}")

#multiplicando por 2 los valores del vector 
result = a * 2 
print(f"Multiplicando por dos el vector {result}")

suma del vector : 10
promedio del vector : 2.5
Multiplicando por dos el vector [2 4 6 8]


In [8]:
#Operaciones entre vectores 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

try:
    c = a + b 
    print(f"resultado : {c}")
except Exception as err:
    print(err)

resultado : [ 6  8 10 12]


<img src="https://raw.githubusercontent.com/greyhatguy007/Machine-Learning-Specialization-Coursera/1a6b6fc2851e6ab2d44f86b84db316a82a70e494/C1%20-%20Supervised%20Machine%20Learning%20-%20Regression%20and%20Classification/week2/Optional%20Labs/images/C1_W2_Lab04_dot_notrans.gif">

In [10]:
#Vector Vector dot product
def my_dot(a, b):
    result = a * b 
    return result.sum()
    
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

print(my_dot(a,b))
print(f"opcion dos : {np.dot(a,b)}")

24
opcion dos : 24


In [11]:
#need for speed: vectores vs loops 
#revisaremos el tiempo que toma la operacion de vector de nuestra funcion vs usando np.dot de numpy 
import time

np.random.seed(1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"np.dot() = {c:.4f}")
print(f"duration : {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f"funcion my_dot = {c:.4f}")
print(f"duration : {1000*(toc-tic):.4f} ms")


np.dot() = 2501072.5817
duration : 18.4121 ms
funcion my_dot = 2501072.5817
duration : 25.9488 ms


In [12]:
#Matrices 
a = np.zeros((5,5)) # 5x5 es la dimension de nuestra matriz
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#como revisamos la dimension? 
a.shape # esta linea de codigo nos retorna la dimension a la matriz consultada

(5, 5)

In [14]:
# cambiando la dimension de una matriz 
b = a.reshape(1,-1)
print(b)

c = np.arange(6).reshape(-1,1)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
#Matrices 
a = np.arange(6).reshape(-1,2)
print(f"a.shape : {a.shape}")

##acceder a un elemento 
print(f"a[2,0].shape : {a[2,0].shape}, a[2,0] = {a[2,0]} ")

##acceder a uina fila 
a[2]

a.shape : (3, 2)
a[2,0].shape : (), a[2,0] = 4 


array([4, 5])

In [39]:
#slicing 
a = np.arange(20).reshape(-1,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [41]:
a[1,2:4]

array([12, 13])